### ISSUE TITLE
Errors of weights.zip and data.zip 

### ISSUE THREAD

**Issue by barrycxg** [JunxingHu/CHOI#1]
Hi, @JunxingHu. It is a great job for reconstructing hand-object interaction. When I reproduce the results, the weights.zip and data.zip cannot be decompressed. Could you reupload these two files or provide the download link.

Looking forward to your reply.

**Comment by JunxingHu** [comment]
Thank you for your interest in our work. We have uploaded the zip files to Baidu Netdisk: https://pan.baidu.com/s/1_wjVPyxAgwRIGV3LC6rHRg (Password：choi).

**Comment by barrycxg** [comment]
Thanks for your patience and reply.
